### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
@DanMiel I've added some tweaks to your code. Please review them on github (not from your email).

**Comment by DanMiel** [comment]
luzpaz:
I'm sorry about responding by email but I couldn't find how to respond through Github. After I saw what you had marked, I noticed many spacing errors in the files. Everything you changed looks fine.
________________________________

**Comment by luzpaz** [comment]
If you look at the bottom of the email there are links. See attached image:

**Comment by luzpaz** [comment]
Screenshot_20220316_132958

**Comment by DanMiel** [comment]
Luzpas:
The changes look good. What do you need for me to do or correct to pass this through? 
A2+ has always lacked constraint tools.

**Comment by luzpaz** [comment]
@DanMiel you can read this [short article](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request) on how to merge PRs

**Comment by DanMiel** [comment]
I take it all I need to do is Push the "Merge pull request" button.
One thing I  missed is Klaus has the version on line 29 of the InitGui file A2P_VERSION = 'V0.4.54b'
should the 54b be changed to 54c? Let me know and I'll push the button.
Thanks.

**Comment by luzpaz** [comment]
You can ping klaus about that. The important this right now is that you get my changes to your files and download them locally. 

If all this is too confusing to you... you can do this tricket:
1. add `.diff` to the end of the URL of this PR
   `https://github.com/DanMiel/A2plus/pull/1` + `.patch`
1. Click > https://github.com/DanMiel/A2plus/pull/1.patch
  It will auto-generate a raw txt diff file https://patch-diff.githubusercontent.com/raw/DanMiel/A2plus/pull/1.patch
1. Make sure you in the correct directory where you local files are located 
1. Then you can run the diff on your local files by using this 1 liner
  `curl -ss https://patch-diff.githubusercontent.com/raw/DanMiel/A2plus/pull/1.patch | git apply`

**Comment by DanMiel** [comment]
Can I just change the code on my hard drive and add those files to https://github.com/DanMiel/A2plus

**Comment by DanMiel** [comment]
I don't know where to put "curl -ss https://patch-diff.githubusercontent.com/raw/DanMiel/A2plus/pull/1.patch | git apply" 
If I'm supposed to put it python, I don't know how that works.

**Comment by luzpaz** [comment]
In the command line interface 

What operating system are you using?

**Comment by DanMiel** [comment]
Windows 10. Do I need to change Directory to where the files are?

**Comment by DanMiel** [comment]
I recieved this error, 'git' is not recognized as an internal or external command,
operable program or batch file.

**Comment by DanMiel** [comment]
Just so you know, I'm a SolidWorks / Visual Basic person. This A2+ stuff is my first python and I'm have not used the python interface because I have to run FreeCAD to get the stuff to run. I'm sure there are better ways to do it.

**Comment by luzpaz** [comment]
Ok, so I'm not sure how to to use linux commands on windows (even though it is possible) But in order not to add complexity to the situation, I'll send you the modified files directly via dropbox 

https://www.dropbox.com/scl/fo/vqxdldarqmaxru00qem3u/h?dl=0&rlkey=a7ps9ow5p03zt325n38lko80w

**Comment by luzpaz** [comment]
I think you'd grok git easier via a UI. Try downloading [gitkraken](https://www.gitkraken.com/)

I created a tutorial https://wiki.freecad.org/Developing_FreeCAD_with_GitKraken

**Comment by DanMiel** [comment]
I got the un-zipped two files from drop box. Do I just add them to https://github.com/DanMiel/A2plus?
If so: Shall I fix the other files and put them up also?

**Comment by luzpaz** [comment]
> I got the un-zipped two files from drop box. Do I just add them to https://github.com/DanMiel/A2plus?

No just add them to your local files. They are my updates to your files.   

As for:  https://github.com/DanMiel/A2plus  
The issues you need to understand is that 
1. your local directory of A2plus needs to be made in to it's own separate git branch so that you aren't working on the master branch
2. that you need to be branching off of the A2plus master branch not a2plus develop branch

>  If so: Shall I fix the other files and put them up also?

What other files are you referring to?

BTW, if you want I can submit a PR for A2plus for you, if this is all too much to learn at once?

**Comment by DanMiel** [comment]
There should five .py files being added to A2+. They all start with CD_ for Constraint Diagnostics, plus two svg files 'ConstraintDiagnostics.svg' and 'updateA2.svg'
I added three lines to a2p_constraint Services. To InitGui.py I added one import statement and 6 or 8 lines in InitGui.py for icons.
I didn't know about the white space formats else I would have fixed them.

This process is more than I had planned on learning in the space of a few days so I think we can procced one of two ways:
1. If you would submit the PR for me, I would appreciate it: or
2. Cancel this one and in a month or so, I can try this again.

**Comment by DanMiel** [comment]
> 1. your local directory of A2plus needs to be made in to it's own separate git branch so that you aren't working on the default branch of the repo. You always make your own branch and then make a pull request to merge that branch back in to the default branch.

So A2plus Local repo does need to be in the FreeCAD/Mod directory


> 2\. that you need to be branching off of the A2plus master branch not a2plus develop branch
> 
> >

That was my mistake I thought I had the master. (I have Parkinson's and with my tremors I don't always click where I think I'm clicking. :)

**Comment by luzpaz** [comment]
I'll submit it the PR and link you to it. 

We can discuss how to setup a `git` environment on the forum if you want, when you have the space and attention (it took me a little bit to understand `git` and I still don't fully)

> So A2plus Local repo does need to be in the FreeCAD/Mod directory

Yes, but IMHO one should clone a 2nd repo somewhere else on your machine. If you're going to develop on it (at least that's my philosophical opinion. Theoretically it's possible and some folks probably just use that repository. It may be easier to test changes on it as well. But it could also be risky and corrupt the repo and mess up things (not too bad though). Again, this is probably a matter of preference, but i prefer to clone git repos somewhere independent of my FreeCAD downloaded addons.

**Comment by DanMiel** [comment]
It looks like some changes were made to A2plus master yesterday. since my changes were attached to the wrong repo, could it overwrite the changes made yesterday?
Dan

**Comment by luzpaz** [comment]
That's what `git rebase` is for. So no worries. Lets see what kbwbe says

**Pull request closed without merging**
